dist: focal
language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9

install:
    - pip install -U pip tox-travis

script:
    - tox

after_success:
    - coverage combine
    - coveralls

notifications:
    email: false

cache:
  pip: true
  directories:
    - eggs/
